language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t stizianel/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true stizianel/react-test npm test

after_success:
    - docker build -t stizianel/multi-client ./client
    - docker build -t stizianel/multi-nginx ./nginx
    - docker build -t stizianel/multi-server ./server
    - docker build -t stizianel/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push to docker hub
    - docker push stizianel/multi-client
    - docker push stizianel/multi-nginx
    - docker push stizianel/multi-server
    - docker push stizianel/multi-worker
deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-2-721326472085
    bucket_path: docker-multi
    on:
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY